export * from "./Leads";
export {default as Static} from "./Static";
export {default as UserLogin} from "./UserLogin";
export {default as ContactUs} from "./ContactUs";
export {default as Activity} from "./Activity";
export {default as Architect} from "./Architect";
export {default as LiveEstimation} from "./LiveEstimation";
export {default as PageNotFound} from "./PageNotFound";
export {default as Testfile} from "./Test";
export {default as UserUpdates} from "./UserUpdates";
